In [33]:
import numpy as np
import pandas as pd

In [34]:
df = pd.DataFrame({'text':['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output':[1,1,0,0]})

In [35]:
df.head()

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [37]:
bow = cv.fit_transform(df['text'])

In [38]:
# print vocabulary

print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [39]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [40]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])

In [41]:
cv = CountVectorizer(ngram_range=(2,2))

In [42]:
bow1 = cv.fit_transform(df['text'])

In [43]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [44]:
print(bow1[0].toarray())
print(bow1[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


In [45]:
cv = CountVectorizer(ngram_range=(3,3))

In [46]:
bow2 = cv.fit_transform(df['text'])

In [47]:
print(cv.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [50]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())
print(tfidf.vocabulary_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}
